version: '3.4'
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asdf1234
      - POSTGRES_DB=payments
    restart: always
    volumes:
      - ./docker_volumes/postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana
    links:
      - postgres
    ports:
      - "5000:3000"

volumes:
  grafana-storage:
