version: '3.4'
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asdf1234
      - POSTGRES_DB=payments
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgres/data
    ports:
      - "5432:5432"
